#!/usr/bin/env php

<?php

// Hides all warnings 
error_reporting(0);
require('taskClass.php');



$task = new Task(file_get_contents('tasks.json'));


if (strtolower($argv[1]) == "add"){
    echo $task->add($argv[2]);
}
else if( strtolower($argv[1]) == "update"){
    echo $task->update($argv[2], $argv[3]);
}
else if( strtolower($argv[1]) == "delete"){
    echo $task->delete($argv[2]);
}
else if((strtolower($argv[1]) == "mark-in-progress") ||  (strtolower($argv[1]) == "mark-done")){
    echo $task->mark($argv[1], $argv[2]);
}
else if( strtolower($argv[1]) == "list"){

    if (isset($argv[2])){
        echo $task->listTasks($argv[2]);
    }
    else{
        echo $task->listTasks();
    }

}
else{
    echo "That command does not exist";
}

?>